name: Deploy to S3

on:
  push:
    branches:
      - main  # change to your branch if needed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v3
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1  # or your region

    - name: Sync files to S3
      run: |
        aws s3 sync . s3://jatinkapoor-cloud-devops-portfolio --delete --acl public-read
